// Fixture rows for the harness, shaped like the views each loader reads.
// Names and places follow wireframes/CONVENTIONS.md in spirit: long enough
// to stress a 390px card.
export const iso = (d, hm = '12:00') => new Date(`${d}T${hm}:00+01:00`).toISOString();

const NAMES = [
  'Amelia Hughes-Montgomery',
  'Tom Baker',
  'Priya Ramanathan',
  'Jack Wilson',
  'Olivia Chen',
  'Mohammed Al-Rashid',
  'Grace O’Connor',
  'Ben Adeyemi',
];

// ---- staff directory ------------------------------------------------------
export const staffRows = NAMES.map((n, i) => ({
  id: 's' + i,
  employee_id: 10230 + i,
  status: [
    'compliant',
    'compliant',
    'blocked',
    'compliant',
    'inactive',
    'compliant',
    'compliant',
    'removed',
  ][i],
  removed: i === 7,
  display_name: i === 7 ? 'Deleted account #10237' : n,
  photo_path: null,
  rating: [4.8, 4.2, 3.9, null, 4.6, 5, 4.4, null][i],
  reliability: [98, 91, 76, null, 95, 100, 88, null][i],
  block_kind: i === 2 ? 'auto_document' : null,
  block_reason: i === 2 ? 'Visa (share code report) expired 20 Sep 2026' : null,
  rtw_branch: i % 2 ? 'student_visa' : 'uk_irish',
  right_to_work_until: i % 2 ? '2027-01-31' : null,
  graduated_at: null,
  wtr_optout: i === 5,
  left_at: i === 4 ? '2026-08-30' : null,
  leave_reason: i === 4 ? 'Moved away' : null,
  role_names:
    i % 3 === 0 ? ['Waiting staff (silver service)', 'Bartender', 'Cloakroom'] : ['Bartender'],
  unresolved_violations: i === 1 ? 2 : 0,
  do_not_return_clients: i === 1 ? ['The Savoy'] : [],
  weekly_cap_hours: i % 2 ? 20 : 48,
  weekly_cap_band: i % 2 ? 'student_term_20' : 'standard_48',
  weekly_booked_hours: i % 2 ? 18.5 : 12,
  weekly_cap_until: i % 2 ? '2026-12-13' : null,
  last_shift_at: iso('2026-09-20', '23:30'),
  released_shift_count: i === 2 ? 3 : 0,
  p45_requested_at: i === 4 ? iso('2026-08-30') : null,
}));

export const studentRows = [1, 3, 5].map((i) => ({
  id: 's' + i,
  display_name: NAMES[i],
  employee_id: 10230 + i,
  photo_path: null,
  status: 'compliant',
  weekly_cap_hours: i === 5 ? 48 : 20,
  weekly_cap_band: i === 5 ? 'student_holiday_48' : 'student_term_20',
  weekly_booked_hours: 18.5,
  right_to_work_until: '2027-01-31',
  graduated_at: null,
  wtr_optout: false,
  term_letter_verified_at: iso('2026-09-01'),
  term_letter_expires_at: '2026-12-13',
  completion_letter_verified_at: i === 5 ? iso('2026-09-10') : null,
  completion_letter_in_review: i === 3,
  below_degree_level: i === 3,
  course_completion_date: i === 5 ? '2026-09-30' : null,
  completion_letter_status: i === 5 ? 'verified' : i === 3 ? 'pending' : null,
  completion_letter_rejection: null,
  completion_date_claimed: i === 3 ? '2026-10-15' : null,
  completion_effective_from: i === 5 ? '2026-09-30' : null,
  wtr_optout_cancelled_from: null,
  optout_eligible: i === 5,
  rtw_days_left: 128,
}));

// ---- clients ----------------------------------------------------------------
export const clientRows = [
  ['The Savoy', 'Eleanor Whitfield', true, false],
  ['Grosvenor House Hotel & Conference Centre', 'Rajesh Patel', false, true],
  ['Kensington Palace Events', 'Harriet Lowe', true, true],
].map(([name, contact, pb, pbf], i) => ({
  id: 'c' + i,
  name,
  contact_name: contact,
  phone: '+44 20 7836 4343',
  staff_contact_point: 'Banqueting office, staff entrance on Carting Lane',
  contact_emails: [
    'events@savoy-london.example.com',
    'banqueting.manager@savoy-london.example.com',
  ],
  pays_breaks: pb,
  pays_buffer: pbf,
  rate_card_roles: ['Waiting staff (silver service)', 'Bartender', 'Cloakroom', 'Runner'],
  rate_card_count: 4,
  event_count: 23 - i * 7,
  avg_margin_pct: i === 2 ? null : 21.4,
}));

export const rateCardRows = [
  ['Waiting staff (silver service)', 18.5, 12.21, 13.68],
  ['Bartender', 19.0, 12.5, 14.01],
  ['Cloakroom attendant', 16.0, 12.21, 13.68],
].map(([role, charge, base, fin], i) => ({
  id: 'rc' + i,
  role_id: 'r' + i,
  role_name: role,
  role_description: 'Plated and silver service at seated dinners',
  charge_rate: charge,
  base_pay_rate: base,
  final_pay_rate: fin,
  margin_per_hour: +(charge - fin).toFixed(2),
  margin_pct: +(((charge - fin) / charge) * 100).toFixed(1),
  dress_codes: ['Black trousers, white shirt, black tie', 'Black polished shoes'],
  section_count: 12 - i * 3,
}));

export const qualifiedRows = [0, 1, 2, 5].map((i) => ({
  staff_id: 's' + i,
  display_name: NAMES[i],
  employee_id: 10230 + i,
  photo_path: null,
  status: 'compliant',
  rating: 4.5,
  reliability: 96,
  role_names: ['Waiting staff (silver service)', 'Bartender'],
  role_ids: ['r0', 'r1'],
  qualification_ids: ['q' + i + 'a', 'q' + i + 'b'],
  do_not_return: i === 2,
  first_granted_at: iso('2026-03-14'),
  last_granted_at: iso('2026-09-12'),
  granted_how: i % 2 ? 'manual' : 'automatic',
  granted_by_name: i % 2 ? 'Sarah Mitchell' : null,
  granted_from_event_title: i % 2 ? null : 'Autumn Gala Dinner — The Savoy Ballroom',
  granted_from_event_date: i % 2 ? null : '2026-09-12',
  notes: i === 2 ? 'Client asked not to send again after late arrival' : null,
}));

export const clientEventRows = [
  ['Autumn Gala Dinner — The Savoy Ballroom', '2026-10-03', 'upcoming'],
  ['Corporate Awards Night', '2026-09-25', 'ongoing'],
  ['Summer Garden Party', '2026-08-14', 'completed'],
  ['Charity Auction Evening', '2026-07-30', 'cancelled'],
].map(([title, d, status], i) => ({
  id: 'e' + i,
  title,
  po_number: i === 1 ? 'PO-2026-00481-SAVOY' : null,
  event_date: d,
  starts_at: iso(d, '17:00'),
  ends_at: iso(d, '23:30'),
  venue_name: 'The Savoy, Strand',
  cancelled_at: status === 'cancelled' ? iso('2026-07-20') : null,
  status,
  section_count: 3,
  roles_summary: 'Waiting staff (silver service) × 12, Bartender × 4, Cloakroom × 2',
  margin_gbp: status === 'cancelled' ? null : 842.5,
  margin_pct: status === 'cancelled' ? null : 22.1,
}));

export const roleOptions = [
  { id: 'r0', name: 'Waiting staff (silver service)', pay_rate: 12.21 },
  { id: 'r1', name: 'Bartender', pay_rate: 12.5 },
  { id: 'r2', name: 'Cloakroom attendant', pay_rate: 12.21 },
];

// ---- staff profile -----------------------------------------------------------
export const profileRow = {
  ...staffRows[1],
  email: 'tom.baker.longname@student.kcl.ac.uk',
  phone: '+44 7700 900123',
  dob: '2004-05-17',
  home_address: 'Flat 4, 27 Lower Marsh, Waterloo, London SE1 7RG',
  share_code: 'W4K 9PX 2LM',
  ni_number_masked: '•• •• •• 45 C',
  has_ni_number: true,
  term_dates: ['2026-09-21/2026-12-11', '2027-01-11/2027-03-26'],
  contract_signed_at: iso('2026-03-01', '10:12'),
  contract_version: 'v3.2',
  joined_at: iso('2026-02-20'),
  quiz_attempts: 2,
  bank_account_holder: 'T BAKER',
  bank_sort_code_masked: '••-••-45',
  bank_account_masked: '••••6789',
  bank_updated_at: iso('2026-03-01'),
  hmrc_statement: 'A',
  hmrc_student_loan: 'plan2',
  hmrc_postgraduate_loan: false,
  hmrc_declared_at: iso('2026-03-01'),
  shifts_worked: 38,
  no_shows: 1,
  feedback_count: 4,
  documents_pending: 1,
  qualification_count: 3,
};

const docBase = {
  superseded: false,
  file_path: 'docs/a.pdf',
  gov_report_path: null,
  expiry_date: null,
  expires_on: null,
  ai_confidence: 0.93,
  needs_manual_review: false,
  rejection_reason: null,
  reviewed_at: iso('2026-02-22'),
  reviewed_by_name: 'Sarah Mitchell',
  share_code: null,
  right_to_work_until: null,
  rtw_no_time_limit: false,
  completion_date: null,
  awarding_institution: null,
  term_dates: null,
};
export const documentRows = [
  {
    ...docBase,
    id: 'd1',
    doc_type: 'passport',
    doc_label: 'Passport',
    review_status: 'verified',
    uploaded_at: iso('2026-02-20'),
    expiry_date: '2031-03-14',
    expires_on: '2031-03-14',
  },
  {
    ...docBase,
    id: 'd2',
    doc_type: 'share_code_report',
    doc_label: 'Share code report',
    review_status: 'verified',
    uploaded_at: iso('2026-02-20'),
    share_code: 'W4K 9PX 2LM',
    right_to_work_until: '2027-01-31',
    expires_on: '2027-01-31',
  },
  {
    ...docBase,
    id: 'd3',
    doc_type: 'term_dates_letter',
    doc_label: 'University term dates letter',
    review_status: 'pending',
    uploaded_at: iso('2026-09-23'),
    reviewed_at: null,
    reviewed_by_name: null,
    term_dates: ['2026-09-21/2026-12-11'],
  },
  {
    ...docBase,
    id: 'd4',
    doc_type: 'completion_letter',
    doc_label: 'Course completion letter',
    review_status: 'rejected',
    uploaded_at: iso('2026-09-01'),
    rejection_reason: 'The letter is not signed by the university registry',
    awarding_institution: 'King’s College London',
  },
];

export const qualificationRows = [
  ['The Savoy', 'Waiting staff (silver service)', 'automatic', false],
  ['The Savoy', 'Bartender', 'manual', false],
  ['Grosvenor House Hotel & Conference Centre', 'Bartender', 'manual', true],
].map(([client, role, how, dnr], i) => ({
  id: 'qu' + i,
  client_id: 'c' + i,
  client_name: client,
  role_id: 'r' + i,
  role_name: role,
  granted_how: how,
  granted_by_name: how === 'manual' ? 'Sarah Mitchell' : null,
  granted_from_event: how === 'automatic' ? 'e0' : null,
  granted_from_event_title: how === 'automatic' ? 'Autumn Gala Dinner — The Savoy Ballroom' : null,
  granted_from_event_date: how === 'automatic' ? '2026-09-12' : null,
  granted_at: iso('2026-09-12'),
  do_not_return: dnr,
  note: dnr ? 'Late twice in August' : null,
}));

export const shiftRows = [
  ['confirmed', null, '2026-10-03', 'worked', null],
  [
    'completed',
    null,
    '2026-09-20',
    'worked',
    { status: 'settled', payableMin: 390, floorApplied: false },
  ],
  ['completed', null, '2026-09-12', 'no_show', null],
  ['cancelled', 'self_cancelled', '2026-09-05', null, null],
  [
    'completed',
    null,
    '2026-08-30',
    'turned_away',
    { status: 'settled', payableMin: 240, floorApplied: true },
  ],
].map(([st, cause, d, kind, pay], i) => ({
  booking_id: 'b' + i,
  booking_status: st,
  cancel_cause: cause,
  self_cancelled: cause === 'self_cancelled',
  starts_at: iso(d, '17:00'),
  ends_at: iso(d, '23:30'),
  role_name: 'Waiting staff (silver service)',
  event_id: 'e' + i,
  event_title: 'Autumn Gala Dinner — The Savoy Ballroom',
  event_date: d,
  client_name: 'Grosvenor House Hotel & Conference Centre',
  venue_name: 'Grosvenor House, 86–90 Park Lane',
  check_in_at: kind === 'worked' && i ? iso(d, '16:54') : null,
  check_out_at: kind === 'worked' && i ? iso(d, '23:34') : null,
  kind: i === 0 ? null : kind,
  pay,
  violation_count: i === 2 ? 1 : 0,
  unresolved_violation_count: i === 2 ? 1 : 0,
}));

export const profileViolationRows = [
  {
    id: 'v1',
    booking_id: 'b2',
    type: 'no_show',
    detected_at: iso('2026-09-12', '17:30'),
    minutes_late: null,
    resolved: false,
    resolved_at: null,
    resolution_note: null,
    resolved_by_name: null,
    starts_at: iso('2026-09-12', '17:00'),
    ends_at: iso('2026-09-12', '23:30'),
    role_name: 'Waiting staff (silver service)',
    event_title: 'Autumn Gala Dinner — The Savoy Ballroom',
    event_date: '2026-09-12',
    client_name: 'The Savoy',
    venue_name: 'The Savoy, Strand',
  },
  {
    id: 'v2',
    booking_id: 'b1',
    type: 'late',
    detected_at: iso('2026-08-12', '17:31'),
    minutes_late: 18,
    resolved: true,
    resolved_at: iso('2026-08-13', '09:00'),
    resolution_note: 'Tube strike — agreed with client',
    resolved_by_name: 'Sarah Mitchell',
    starts_at: iso('2026-08-12', '17:00'),
    ends_at: iso('2026-08-12', '23:30'),
    role_name: 'Bartender',
    event_title: 'Corporate Awards Night',
    event_date: '2026-08-12',
    client_name: 'Grosvenor House Hotel & Conference Centre',
    venue_name: 'Grosvenor House, 86–90 Park Lane',
  },
];

export const feedbackRows = [
  [
    'client',
    5,
    'Tom was brilliant with the VIP table all night — please send him again for the winter ball.',
    true,
    false,
  ],
  [
    'office',
    3,
    'Arrived on time but left the section early without telling the supervisor.',
    false,
    true,
  ],
  ['client', 4, null, false, false],
].map(([kind, rating, text, unread, editable], i) => ({
  id: 'f' + i,
  author_kind: kind,
  rating,
  text,
  created_at: iso('2026-09-2' + i, '10:00'),
  updated_at: i === 1 ? iso('2026-09-22', '11:00') : null,
  read_at: unread ? null : iso('2026-09-22'),
  read_by_name: unread ? null : 'Sarah Mitchell',
  unread,
  counts_toward_rating: !unread,
  editable,
  deletable: editable,
  author_id: 'a' + i,
  author_name: kind === 'office' ? 'Sarah Mitchell' : 'Eleanor Whitfield',
  staff_id: 's1',
  staff_name: i === 2 ? 'Amelia Hughes-Montgomery' : 'Tom Baker',
  employee_id: 10231,
  staff_removed: false,
  staff_removed_at: null,
  event_id: i === 1 ? null : 'e0',
  event_title: i === 1 ? null : 'Autumn Gala Dinner — The Savoy Ballroom',
  event_date: i === 1 ? null : '2026-09-12',
  venue_name: 'The Savoy, Strand',
  client_id: 'c0',
  client_name: 'Grosvenor House Hotel & Conference Centre',
  role_names: 'Waiting staff (silver service)',
}));

export const referenceRows = [
  {
    id: 'rf1',
    name: 'Dr Helen Carter',
    relationship: 'Personal tutor',
    phone: '+44 20 7848 1234',
    email: 'helen.carter@kcl.ac.uk',
  },
  {
    id: 'rf2',
    name: 'James O’Neill',
    relationship: 'Former manager, Pret A Manger',
    phone: '+44 7700 900456',
    email: 'james.oneill@example.com',
  },
];
export const declarationRows = [
  {
    id: 'dc1',
    source: 'onboarding',
    answer: false,
    details: null,
    conviction_date: null,
    review_status: 'verified',
    declared_at: iso('2026-02-20'),
    reviewed_at: iso('2026-02-21'),
    review_note: null,
    superseded: false,
  },
  {
    id: 'dc2',
    source: 'in_employment',
    answer: true,
    details: 'Driving offence, 2025 — fine only',
    conviction_date: '2025-06-01',
    review_status: 'pending',
    declared_at: iso('2026-09-24'),
    reviewed_at: null,
    review_note: null,
    superseded: false,
  },
];

// ---- onboarding -------------------------------------------------------------
const candBase = {
  email: 'candidate@example.com',
  phone: '+44 7700 900789',
  dob: '2005-01-12',
  age: 21,
  applied_age_band: '18-24',
  photo_path: null,
  gdpr_consent_at: iso('2026-09-01'),
  employee_id: null,
  rtw_branch: 'student_visa',
  right_to_work_until: '2027-01-31',
  share_code: 'W4K 9PX 2LM',
  activated: true,
  role_names: ['Waiting staff (silver service)', 'Bartender'],
  role_ids: ['r0', 'r1'],
  willo_linked: true,
  willo_review_url: 'https://willo.example/review/1',
  willo_invited_at: iso('2026-09-02'),
  willo_answers_done: 5,
  willo_answers_total: 5,
  willo_completed_at: iso('2026-09-03'),
  willo_decision: 'accepted',
  willo_decided_at: iso('2026-09-04'),
  willo_decided_via: 'office',
  docs_total: 4,
  docs_verified: 2,
  docs_pending: 1,
  docs_rejected: 1,
  last_doc_rejected_at: iso('2026-09-10'),
  docs_missing: ['Proof of address'],
  quiz_blockers: null,
  declaration_answer: false,
  declaration_status: 'verified',
  quiz_attempts_used: 1,
  quiz_best_score: 80,
  quiz_passed_at: null,
  hmrc_submitted_at: null,
  references_count: 1,
  bank_saved: false,
  ni_entered: false,
  contract_signed_at: null,
  contract_version: null,
  rejected_at: null,
  rejected_from: null,
  rejection_cause: null,
  rejection_reason: null,
  rejected_by_name: null,
  activated_at: iso('2026-09-02'),
  additional_info_done_at: null,
  quiz_scores: [80],
};
const STAGES = [
  'interview_requested',
  'interview_completed',
  'documents',
  'documents',
  'quiz',
  'additional_info',
  'contract',
  'rejected',
];
export const candidateRows = NAMES.map((n, i) => ({
  ...candBase,
  id: 'cd' + i,
  first_name: n.split(' ')[0],
  last_name: n.split(' ').slice(1).join(' '),
  display_name: n,
  status: STAGES[i],
  stage_entered_at: iso('2026-09-' + String(10 + i).padStart(2, '0')),
  onboarding_started_at: iso('2026-09-01'),
  applied_at: iso('2026-09-01'),
  rejected_at: STAGES[i] === 'rejected' ? iso('2026-09-20') : null,
  rejected_from: STAGES[i] === 'rejected' ? 'quiz' : null,
  rejection_cause: STAGES[i] === 'rejected' ? 'quiz_failed' : null,
  rejection_reason: STAGES[i] === 'rejected' ? 'Failed the quiz three times' : null,
}));
export const returningRows = [
  {
    application_id: 'ap1',
    applied_at: iso('2026-09-22'),
    applicant_name: 'Jack Wilson',
    matched_on: 'email_dob',
    staff_id: 's3',
    existing_name: 'Jack Wilson',
    employee_id: 10233,
    status: 'inactive',
    block_kind: null,
    block_reason: null,
    rating: 4.1,
    reliability: 92,
    shifts_worked: 17,
  },
];

// ---- event board ------------------------------------------------------------
const person = (i) => ({
  staffId: 's' + i,
  name: NAMES[i].split(' ')[0] + ' ' + NAMES[i].split(' ')[1][0] + '.',
  roles: ['Waiting staff (silver service)', 'Bartender'],
});
const booking = (i, status, extra = {}) => ({
  ...person(i),
  bookingId: 'bk' + i + status,
  status,
  source: 'auto_assign',
  createdAt: iso('2026-09-20'),
  confirmedAt: status === 'confirmed' ? iso('2026-09-21') : null,
  dayBeforeConfirmedAt: status === 'confirmed' && i % 2 ? iso('2026-10-02', '09:00') : null,
  appliedAt: null,
  qualified: i % 2 === 0,
  noShow: false,
  reconfirmRequired: i === 3,
  ...extra,
});
const pool = [4, 5, 6].map((i, k) => ({
  ...person(i),
  rank: k + 1,
  wave: k === 0 ? 1 : 2,
  qualified: k === 0,
  breakdown: { show: 90, rating: 80, proximity: 60, fair: 50, venue: 20, total: 71.5 - k * 6 },
  input: { reliability: 97, rating: 4.6, distanceKm: 6.2, futureShifts: 2, venueTimes: 3 },
  appliedAt: k === 1 ? iso('2026-09-22') : null,
  applicationId: k === 1 ? 'bkapp' : null,
}));
const unavailable = [
  {
    ...person(2),
    reason: 'blocked',
    label: 'Blocked — compliance',
    detail: 'not compliant, so not invitable (§2.12)',
    tone: 'coral',
    appliedAt: null,
  },
  {
    ...person(7),
    reason: 'hours_limit',
    label: 'Weekly hours limit',
    detail: 'would exceed the 20 h term-time cap (RULE-20)',
    tone: 'amber',
    appliedAt: null,
  },
];
export const boardEvent = {
  id: '11111111-1111-4111-8111-111111111111',
  title: 'Autumn Gala Dinner — The Savoy Ballroom',
  date: '2026-10-03',
  clientId: 'c0',
  clientName: 'Grosvenor House Hotel & Conference Centre',
  venueName: 'The Savoy, Strand',
  venueAddress: 'Strand, London WC2R 0EZ',
  poNumber: 'PO-2026-00481-SAVOY',
  notes: 'Guests arrive 18:30. Speeches at 21:00 — no service during speeches.',
  onsiteContact: 'Eleanor Whitfield · +44 20 7836 4343',
  autoAssign: true,
  paysBreaks: false,
  paysBuffer: false,
  cancelledAt: null,
  cancelReason: '',
  payrollExportedAt: null,
  weights: { show: 0.3, rating: 0.25, proximity: 0.25, fair: 0.1, venue: 0.1 },
  sections: [
    {
      id: 'sec1',
      roleId: 'r0',
      roleName: 'Waiting staff (silver service)',
      startsAt: iso('2026-10-03', '17:00'),
      endsAt: iso('2026-10-03', '23:30'),
      headcount: 6,
      buffer: 1,
      chargeRate: 18.5,
      payRate: 12.21,
      dressCode: 'Black trousers, white shirt, black tie; black polished shoes',
      autoAssign: true,
      allocationPerHour: 2,
      confirmed: [booking(0, 'confirmed'), booking(1, 'confirmed'), booking(3, 'confirmed')],
      invited: [booking(5, 'invited'), booking(6, 'invited', { appliedAt: iso('2026-09-22') })],
      applied: [],
      pool,
      poolProblem: null,
      unavailable,
    },
    {
      id: 'sec2',
      roleId: 'r1',
      roleName: 'Bartender',
      startsAt: iso('2026-10-03', '18:00'),
      endsAt: iso('2026-10-04', '00:30'),
      headcount: 2,
      buffer: 0,
      chargeRate: 19,
      payRate: 12.5,
      dressCode: 'All black',
      autoAssign: false,
      allocationPerHour: 1,
      confirmed: [booking(4, 'confirmed'), booking(2, 'confirmed')],
      invited: [],
      applied: [],
      pool: [],
      poolProblem: null,
      unavailable: [],
    },
  ],
};

// ---- shift builder ----------------------------------------------------------
export const reference = {
  clients: clientRows.map((c) => ({
    id: c.id,
    name: c.name,
    staffContactPoint: c.staff_contact_point,
    contactEmails: c.contact_emails,
    paysBreaks: c.pays_breaks,
    paysBuffer: c.pays_buffer,
    rateCard: {
      r0: {
        chargeRate: 18.5,
        dressCodes: ['Black trousers, white shirt, black tie', 'Black polished shoes'],
      },
      r1: { chargeRate: 19, dressCodes: ['All black'] },
      r2: { chargeRate: 16, dressCodes: [] },
    },
  })),
  venues: [
    {
      id: 'v0',
      name: 'The Savoy, Strand',
      address: 'Strand, London WC2R 0EZ',
      venueType: 'hotel',
      venueTypeLabel: 'Hotel',
      geofenceRadiusM: 150,
    },
    {
      id: 'v1',
      name: 'Grosvenor House',
      address: '86–90 Park Lane, London W1K 7TN',
      venueType: 'hotel',
      venueTypeLabel: 'Hotel',
      geofenceRadiusM: 200,
    },
  ],
  roles: roleOptions.map((r) => ({ id: r.id, name: r.name, payRate: r.pay_rate })),
};
export const savedEvent = {
  id: '11111111-1111-4111-8111-111111111111',
  clientId: 'c0',
  venueId: 'v0',
  title: 'Autumn Gala Dinner — The Savoy Ballroom',
  date: '2026-10-03',
  poNumber: 'PO-2026-00481-SAVOY',
  onsiteContact: 'Eleanor Whitfield · +44 20 7836 4343',
  notes: 'Guests arrive 18:30.',
  autoAssign: true,
  cancelledAt: null,
  sections: [
    {
      id: 'sec1',
      roleId: 'r0',
      start: '17:00',
      end: '23:30',
      headcount: 6,
      buffer: 1,
      chargeRate: 18.5,
      payRate: 12.21,
      dressCode: 'Black trousers, white shirt, black tie',
      autoAssign: true,
      allocationPerHour: 2,
      confirmed: 3,
      booked: 5,
    },
    {
      id: 'sec2',
      roleId: 'r1',
      start: '18:00',
      end: '00:30',
      headcount: 2,
      buffer: 0,
      chargeRate: 19,
      payRate: 12.5,
      dressCode: 'All black',
      autoAssign: false,
      allocationPerHour: 1,
      confirmed: 2,
      booked: 2,
    },
  ],
};

// ---- reports ----------------------------------------------------------------
export const financeRows = [
  ...clientRows.map((c, i) => ({
    group_label: c.name,
    group_key: c.id,
    is_total: false,
    events: ['Autumn Gala Dinner — The Savoy Ballroom', 'Corporate Awards Night'],
    cancelled_events: i === 2 ? ['Charity Auction Evening'] : [],
    event_count: 2,
    payable_min: 12480,
    base: 2539.68,
    holiday: 306.54,
    payroll: 2846.22,
    invoicing: 3848,
    margin: 1001.78,
    margin_pct: 26.0,
    actual_sections: 4,
    forecast_sections: i,
    pending: i === 1 ? 2 : 0,
  })),
  {
    group_label: null,
    group_key: null,
    is_total: true,
    events: null,
    cancelled_events: null,
    event_count: 6,
    payable_min: 37440,
    base: 7619.04,
    holiday: 919.62,
    payroll: 8538.66,
    invoicing: 11544,
    margin: 3005.34,
    margin_pct: 26.0,
    actual_sections: 12,
    forecast_sections: 3,
    pending: 2,
  },
];
export const payrollLines = shiftRows.slice(1).map((s, i) => ({
  employee_id: 10231,
  staff_name: NAMES[i],
  event_title: s.event_title,
  client_name: s.client_name,
  role_name: s.role_name,
  shift_date: s.event_date,
  starts_at: s.starts_at,
  ends_at: s.ends_at,
  check_in_at: s.check_in_at,
  check_out_at: s.check_out_at,
  kind: s.kind === 'no_show' ? 'worked' : s.kind,
  unpaid_break_min: 30,
  payable_min: 360,
  rate: 12.21,
  base: 73.26,
  holiday: 8.84,
  total: 82.1,
  in_export: i !== 1,
  booking_id: s.booking_id,
  shift_id: 'sh' + i,
  staff_id: 's' + i,
  removed: false,
  status: i === 1 ? 'pending' : 'settled',
  attempted_at: null,
  no_check_out_unresolved: i === 1,
  late_check_in: i === 2,
  early_check_out: false,
  worked_min: 390,
  floor_applied: i === 3,
  exported_at: null,
  exported_payable_min: null,
  exported_total: null,
  changed_since_export: false,
}));
export const payrollPeople = [
  ...NAMES.slice(0, 4).map((n, i) => ({
    staff_id: 's' + i,
    employee_id: 10230 + i,
    staff_name: n,
    removed: false,
    is_total: false,
    workers: 1,
    shifts: 3,
    pending: i === 1 ? 1 : 0,
    turned_away: i === 3 ? 1 : 0,
    payable_min: 1080,
    break_min: 90,
    base: 219.78,
    holiday: 26.53,
    total: 246.31,
    changed_since_export: 0,
  })),
  {
    staff_id: null,
    employee_id: null,
    staff_name: null,
    removed: null,
    is_total: true,
    workers: 4,
    shifts: 12,
    pending: 1,
    turned_away: 1,
    payable_min: 4320,
    break_min: 360,
    base: 879.12,
    holiday: 106.12,
    total: 985.24,
    changed_since_export: 0,
  },
];
export const reportSends = [
  {
    id: 1,
    kind: 'payroll',
    period_start: '2026-09-14',
    period_end: '2026-09-20',
    status: 'sent',
    sent_at: iso('2026-09-21', '09:00'),
    created_at: iso('2026-09-21', '09:00'),
    row_count: 42,
    held_count: 1,
    error: null,
  },
  {
    id: 2,
    kind: 'payroll',
    period_start: '2026-09-07',
    period_end: '2026-09-13',
    status: 'failed',
    sent_at: null,
    created_at: iso('2026-09-14', '09:00'),
    row_count: 38,
    held_count: 0,
    error: 'SMTP 550 mailbox unavailable',
  },
];
export const starters = NAMES.slice(0, 3).map((n, i) => ({
  staff_name: n,
  employee_id: 10230 + i,
  ni_number: 'QQ 12 34 56 C',
  home_address: 'Flat 4, 27 Lower Marsh, Waterloo',
  postcode: 'SE1 7RG',
  country: 'United Kingdom',
  date_of_birth: '2004-05-17',
  gender: 'Female',
  first_shift_date: '2026-09-20',
  hmrc_statement: 'A',
  student_loan: 'Plan 2',
  staff_id: 's' + i,
  removed: false,
  period_start: '2026-09-14',
  period_end: '2026-09-20',
}));

// ---- roles, venues ---------------------------------------------------------
export const roleRows = [
  ['Waiting staff (silver service)', 12.21, 12, 30],
  ['Bartender', 12.5, 8, 14],
  ['Cloakroom attendant', 12.21, 3, 0],
  ['Head waiter / section supervisor (black tie events)', 14.5, 0, 0],
].map(([name, pay, cards, sections], i) => ({
  id: 'r' + i,
  name,
  description: i === 3 ? null : 'Plated and silver service at seated dinners and banquets',
  pay_rate: pay,
  holiday_rate: +(pay * 0.1207).toFixed(2),
  final_rate: +(pay * 1.1207).toFixed(2),
  rate_card_count: cards,
  section_count: sections,
}));
export const venueRows = [
  [
    'The Savoy, Strand',
    'Strand, London WC2R 0EZ',
    'hotel',
    'Hotel',
    150,
    150,
    51.5104,
    -0.1204,
    23,
    2,
  ],
  [
    'Grosvenor House Hotel & Conference Centre',
    '86–90 Park Lane, London W1K 7TN',
    'hotel',
    'Hotel',
    150,
    250,
    51.5095,
    -0.1557,
    12,
    0,
  ],
  [
    'Kensington Palace Orangery',
    'Kensington Gardens, London W8 4PX',
    'outdoor',
    'Outdoor / park',
    400,
    400,
    51.5058,
    -0.1877,
    0,
    1,
  ],
].map(([name, address, type, label, def, r, lat, lng, past, up], i) => ({
  id: 'v' + i,
  name,
  address,
  venue_type: type,
  venue_type_label: label,
  default_radius_m: def,
  geofence_radius_m: r,
  lat,
  lng,
  events_past: past,
  events_upcoming: up,
}));
export const venueTypes = [
  { key: 'hotel', label: 'Hotel', default_radius_m: 150, sort_order: 1 },
  { key: 'stadium', label: 'Stadium / arena', default_radius_m: 500, sort_order: 2 },
  { key: 'outdoor', label: 'Outdoor / park', default_radius_m: 400, sort_order: 3 },
];

// ---- client portal ---------------------------------------------------------
export const portalEvents = [
  ['e0', 'Autumn Gala Dinner — The Savoy Ballroom', '2026-10-03', 'upcoming'],
  ['e1', 'Corporate Awards Night', '2026-09-25', 'ongoing'],
  ['e2', 'Summer Garden Party', '2026-08-14', 'completed'],
  ['e3', 'Charity Auction Evening', '2026-07-30', 'cancelled'],
].map(([id, title, d, status]) => ({
  id,
  title,
  venue_name: 'The Savoy, Strand',
  venue_address: 'Strand, London WC2R 0EZ',
  event_date: d,
  po_number: id === 'e1' ? 'PO-2026-00481-SAVOY' : null,
  onsite_contact: 'Eleanor Whitfield · +44 20 7836 4343',
  starts_at: iso(d, '17:00'),
  ends_at: iso(d, '23:30'),
  status,
}));
export const portalSections = portalEvents.flatMap((e) => [
  {
    shift_id: e.id + 'a',
    event_id: e.id,
    role: 'Waiting staff (silver service)',
    starts_at: e.starts_at,
    ends_at: e.ends_at,
    headcount: 6,
    confirmed: 5,
  },
  {
    shift_id: e.id + 'b',
    event_id: e.id,
    role: 'Bartender',
    starts_at: iso(e.event_date, '18:00'),
    ends_at: iso(e.event_date, '23:59'),
    headcount: 2,
    confirmed: 2,
  },
]);
export const portalLineup = portalEvents.flatMap((e) =>
  NAMES.slice(0, 6).map((n, i) => ({
    booking_id: e.id + 'l' + i,
    event_id: e.id,
    role: i < 4 ? 'Waiting staff (silver service)' : 'Bartender',
    starts_at: e.starts_at,
    ends_at: e.ends_at,
    name: n.split(' ')[0] + ' ' + n.split(' ')[1][0] + '.',
    photo_path: null,
    sort_key: n,
    feedback_given: i === 0,
  })),
);
