// Screen registry for the harness. `page` is relative to the worktree.
const O = 'apps/office/app/';
const C = 'apps/client/app/';

const iso = (d, hm = '12:00') => new Date(`${d}T${hm}:00+01:00`).toISOString();

const queueBase = {
  employee_id: 10231,
  is_candidate: false,
  block_kind: null,
  block_reason: null,
  rtw_branch: 'uk_irish',
  photo_path: null,
  file_path: 'docs/x.pdf',
  ai_confidence: 0.94,
  needs_manual_review: false,
  expiry_date: '2031-03-14',
  term_dates: null,
  doc_right_to_work_until: null,
  share_code: null,
  awarding_institution: null,
  is_reupload: false,
  previous_rejection: null,
  declaration_source: null,
  declaration_details: null,
  conviction_date: null,
  staff_right_to_work_until: null,
  evidence_form: null,
  completion_date_claimed: null,
  mime_type: 'application/pdf',
  size_bytes: 482113,
  review_reason: null,
  manual_review_reason: null,
};
const queue = [
  {
    ...queueBase,
    kind: 'document',
    item_id: 'q1',
    staff_id: 's1',
    display_name: 'Amelia Hughes-Montgomery',
    status: 'documents',
    is_candidate: true,
    item_type: 'passport',
    item_label: 'Passport',
    submitted_at: iso('2026-09-22', '09:14'),
  },
  {
    ...queueBase,
    kind: 'document',
    item_id: 'q2',
    staff_id: 's2',
    display_name: 'Priya Ramanathan',
    status: 'compliant',
    rtw_branch: 'student_visa',
    item_type: 'share_code_report',
    item_label: 'Share code report',
    share_code: 'W4K 9PX 2LM',
    ai_confidence: 0.62,
    submitted_at: iso('2026-09-23', '14:02'),
    rtw_check_status: 'needs_review',
    rtw_check_source: 'govuk',
    rtw_check_reason: 'Name on the report differs from the profile',
    rtw_manual_allowed: true,
  },
  {
    ...queueBase,
    kind: 'document',
    item_id: 'q3',
    staff_id: 's3',
    display_name: 'Mohammed Al-Rashid',
    status: 'compliant',
    rtw_branch: 'student_visa',
    item_type: 'completion_letter',
    item_label: 'Course completion letter',
    evidence_form: 'letter',
    completion_date_claimed: '2026-10-02',
    awarding_institution: 'King’s College London',
    ai_confidence: null,
    needs_manual_review: true,
    manual_review_reason: 'letter expired',
    is_reupload: true,
    previous_rejection: 'Letter unsigned',
    submitted_at: iso('2026-09-24', '08:40'),
  },
  {
    ...queueBase,
    kind: 'declaration',
    item_id: 'q4',
    staff_id: 's4',
    display_name: 'Tom Baker',
    status: 'blocked',
    block_kind: 'conviction_review',
    block_reason: 'Declared a conviction',
    item_type: 'criminal_declaration',
    item_label: 'Criminal declaration',
    declaration_source: 'in_employment',
    declaration_details: 'Driving offence, 2025 — fine only',
    conviction_date: '2025-06-01',
    file_path: null,
    ai_confidence: null,
    submitted_at: iso('2026-09-24', '17:21'),
  },
];
const radarRow = (i, name, label, exp, days, state) => ({
  staff_id: 's' + i,
  display_name: name,
  employee_id: 10200 + i,
  rtw_branch: 'student_visa',
  status: state === 'expired' ? 'blocked' : 'compliant',
  block_kind: state === 'expired' ? 'auto_document' : null,
  photo_path: null,
  doc_id: 'd' + i,
  doc_type: 'term_dates_letter',
  doc_label: label,
  expires_on: exp,
  days_left: days,
  state,
  n1_at: iso('2026-08-25'),
  n2_at: days < 14 ? iso('2026-09-11') : null,
  n3_at: days < 7 ? iso('2026-09-18') : null,
  n4_at: days <= 0 ? iso('2026-09-25') : null,
  replacement_in_review: i === 2,
});
const radar = [
  radarRow(1, 'Olivia Chen', 'Biometric residence permit', '2026-09-20', -5, 'expired'),
  radarRow(2, 'Priya Ramanathan', 'University term dates letter', '2026-09-30', 5, 'expiring'),
  radarRow(3, 'Jack Wilson', 'Visa (share code report)', '2026-10-21', 26, 'expiring'),
  radarRow(4, 'Grace O’Connor', 'Passport', '2029-01-10', 838, 'valid'),
];
const warnings = [
  {
    id: 1,
    at: iso('2026-09-24', '11:02'),
    booking_id: 'b1',
    staff_id: 's2',
    worker: 'Priya Ramanathan',
    employee_id: 10202,
    event_title: 'Autumn Gala Dinner — The Savoy Ballroom',
    starts_at: iso('2026-09-27', '17:00'),
    cap_hours: 20,
    band: 'term',
    booked_hours: 18.5,
    shift_hours: 6.5,
  },
];
const complianceDb = {
  compliance_review_queue_v: queue,
  compliance_radar_v: radar,
  rota_guard_warnings_v: warnings,
  settings: [{ value: 'warn' }],
  'rpc:rtw_check_enabled': true,
};

import * as R from './rows.mjs';
import extra from './extra.mjs';

const PROFILE = O + 'staff/[id]/page.tsx';
const profileDb = {
  staff_profile_v: [R.profileRow],
  staff_documents_v: R.documentRows,
  staff_client_qualifications_v: R.qualificationRows,
  staff_shift_history_v: R.shiftRows,
  staff_violations_v: R.profileViolationRows,
  violations: R.profileViolationRows,
  feedback_entries_v: R.feedbackRows,
  staff_references: R.referenceRows,
  criminal_declarations: R.declarationRows,
  roles: R.roleOptions,
  clients: R.clientRows,
  profiles: [{ full_name: 'Sarah Mitchell' }],
  'rpc:staff_account_activated': false,
  staff: [{ home_location_stale: true }],
  compliance_review_queue_v: [queue[1]],
};
const profileTab = (tab) => ({
  app: 'office',
  page: PROFILE,
  params: { id: 's1' },
  pathname: '/staff/s1',
  db: profileDb,
  patch: [['staff/[id]/ProfileScreen.tsx', "useState<Tab>('overview')", `useState<Tab>('${tab}')`]],
});
const portalDb = {
  client_events_v: R.portalEvents,
  client_role_sections_v: R.portalSections,
  client_lineup_v: R.portalLineup,
  client_company_v: [{ name: 'Grosvenor House Hotel & Conference Centre' }],
  profiles: [{ full_name: 'Eleanor Whitfield' }],
  client_event_documents_v: [],
};

const base = {
  checkin: { app: 'office', page: O + 'checkin/page.tsx', pathname: '/checkin' },
  compliance: {
    app: 'office',
    page: O + 'compliance/page.tsx',
    pathname: '/compliance',
    db: complianceDb,
  },
  'compliance-radar': {
    app: 'office',
    page: O + 'compliance/page.tsx',
    pathname: '/compliance',
    search: { tab: 'radar' },
    db: complianceDb,
  },
  staff: {
    app: 'office',
    page: O + 'staff/page.tsx',
    pathname: '/staff',
    db: { staff_directory_v: R.staffRows, student_visa_v: R.studentRows },
  },
  'staff-students': {
    app: 'office',
    page: O + 'staff/page.tsx',
    pathname: '/staff',
    search: { view: 'student' },
    db: { staff_directory_v: R.staffRows, student_visa_v: R.studentRows },
  },
  'staff-profile': profileTab('overview'),
  'staff-profile-documents': profileTab('documents'),
  'staff-profile-qualification': profileTab('qualification'),
  'staff-profile-shifts': profileTab('shifts'),
  'staff-profile-feedback': profileTab('feedback'),
  clients: {
    app: 'office',
    page: O + 'clients/page.tsx',
    pathname: '/clients',
    db: { clients_directory_v: R.clientRows },
  },
  'client-card': {
    app: 'office',
    page: O + 'clients/[id]/page.tsx',
    params: { id: 'c1' },
    pathname: '/clients/c1',
    db: {
      clients_directory_v: [R.clientRows[1]],
      clients_rate_card_v: R.rateCardRows,
      clients_qualified_staff_v: R.qualifiedRows,
      clients_event_list_v: R.clientEventRows,
      roles: R.roleOptions,
      staff_directory_v: R.staffRows,
    },
  },
  onboarding: {
    app: 'office',
    page: O + 'onboarding/page.tsx',
    pathname: '/onboarding',
    db: {
      onboarding_candidates_v: R.candidateRows,
      onboarding_returning_v: R.returningRows,
      roles: R.roleOptions,
    },
  },
  'onboarding-candidate': {
    app: 'office',
    page: O + 'onboarding/[id]/page.tsx',
    params: { id: 'cd2' },
    pathname: '/onboarding/cd2',
    db: {
      onboarding_candidates_v: [R.candidateRows[2]],
      staff_profile_v: [R.profileRow],
      staff_documents_v: R.documentRows,
      criminal_declarations: R.declarationRows,
      staff_references: R.referenceRows,
      quiz_attempts: [
        { id: 'qa1', attempt_no: 1, score: 80, passed: false, taken_at: R.iso('2026-09-12') },
      ],
      hmrc_checklists: [],
      applications: [
        {
          created_at: R.iso('2026-09-01'),
          consented_at: R.iso('2026-09-01'),
          outcome: 'candidate_created',
          matched_on: null,
        },
      ],
      roles: R.roleOptions,
    },
  },
  'onboarding-contract': {
    app: 'office',
    page: O + 'onboarding/[id]/page.tsx',
    params: { id: 'cd6' },
    pathname: '/onboarding/cd6',
    db: {
      onboarding_candidates_v: [
        {
          ...R.candidateRows[6],
          hmrc_submitted_at: R.iso('2026-09-14'),
          references_count: 2,
          bank_saved: true,
          ni_entered: true,
          quiz_passed_at: R.iso('2026-09-13'),
          additional_info_done_at: R.iso('2026-09-15'),
        },
      ],
      staff_profile_v: [R.profileRow],
      staff_documents_v: R.documentRows,
      criminal_declarations: R.declarationRows,
      staff_references: R.referenceRows,
      quiz_attempts: [
        { id: 'qa1', attempt_no: 1, score: 90, passed: true, taken_at: R.iso('2026-09-13') },
      ],
      hmrc_checklists: [
        {
          q1_other_job: false,
          q2_pension: false,
          q3_since_6_april: true,
          statement: 'A',
          student_loan: 'plan2',
          postgraduate_loan: false,
          declared: true,
          submitted_at: R.iso('2026-09-14'),
        },
      ],
      applications: [
        {
          created_at: R.iso('2026-09-01'),
          consented_at: R.iso('2026-09-01'),
          outcome: 'candidate_created',
          matched_on: null,
        },
      ],
      roles: R.roleOptions,
      contract_versions: [
        {
          version: 'v3.2',
          title: 'Zero-hours worker agreement',
          body: 'This agreement is between The Hospitality Company and you.\n\n1. Engagement. You are engaged on a zero-hours basis.',
          is_placeholder: true,
        },
      ],
    },
  },
  'event-board': {
    app: 'office',
    page: O + 'events/[id]/page.tsx',
    params: { id: R.boardEvent.id },
    pathname: '/events/' + R.boardEvent.id,
  },
  'shift-builder': {
    app: 'office',
    page: O + 'events/new/page.tsx',
    search: { from: R.savedEvent.id },
    pathname: '/events/new',
  },
  'shift-builder-blank': {
    app: 'office',
    page: O + 'events/new/page.tsx',
    pathname: '/events/new',
  },
  reports: {
    app: 'office',
    page: O + 'reports/page.tsx',
    pathname: '/reports',
    search: { tab: 'financial' },
    db: { 'rpc:finance_report': R.financeRows, report_sends: R.reportSends },
  },
  'reports-payroll': {
    app: 'office',
    page: O + 'reports/page.tsx',
    pathname: '/reports',
    search: { tab: 'payroll' },
    db: {
      'rpc:payroll_report': R.payrollLines,
      'rpc:payroll_report_people': R.payrollPeople,
      report_sends: R.reportSends,
    },
  },
  'reports-newstarter': {
    app: 'office',
    page: O + 'reports/page.tsx',
    pathname: '/reports',
    search: { tab: 'newstarter' },
    db: { 'rpc:new_starter_report': R.starters, report_sends: R.reportSends },
  },
  roles: {
    app: 'office',
    page: O + 'roles/page.tsx',
    pathname: '/roles',
    db: { role_directory_v: R.roleRows },
  },
  venues: {
    app: 'office',
    page: O + 'venues/page.tsx',
    pathname: '/venues',
    db: { venue_directory_v: R.venueRows, venue_types: R.venueTypes },
  },
  feedback: {
    app: 'office',
    page: O + 'feedback/page.tsx',
    pathname: '/feedback',
    db: {
      feedback_entries_v: R.feedbackRows,
      clients: R.clientRows,
      feedback_authors_v: [{ author_id: 'a1', author_name: 'Sarah Mitchell' }],
      profiles: [{ full_name: 'Sarah Mitchell' }],
    },
  },
  'feedback-office': {
    app: 'office',
    page: O + 'feedback/page.tsx',
    pathname: '/feedback',
    search: { tab: 'office' },
    db: {
      feedback_entries_v: R.feedbackRows,
      clients: R.clientRows,
      feedback_authors_v: [{ author_id: 'a1', author_name: 'Sarah Mitchell' }],
      profiles: [{ full_name: 'Sarah Mitchell' }],
    },
  },
  'loading-dashboard': { app: 'office', page: O + 'dashboard/loading.tsx', pathname: '/dashboard' },
  'loading-staff-profile': {
    app: 'office',
    page: O + 'staff/[id]/loading.tsx',
    pathname: '/staff',
  },
  'loading-onboarding': {
    app: 'office',
    page: O + 'onboarding/loading.tsx',
    pathname: '/onboarding',
  },
  'loading-event-new': { app: 'office', page: O + 'events/new/loading.tsx', pathname: '/events' },
  'loading-portal': {
    app: 'client',
    page: C + 'client/loading.tsx',
    layouts: [C + 'client/layout.tsx'],
    pathname: '/client',
    db: portalDb,
  },
  settings: { app: 'office', page: O + 'settings/page.tsx', pathname: '/settings' },
  'settings-dirty': {
    app: 'office',
    page: O + 'settings/page.tsx',
    pathname: '/settings',
    patch: [
      [
        'settings/SettingsScreen.tsx',
        "className={titles.length === 0 ? 'hide' : undefined}",
        'className={undefined}',
      ],
      [
        'settings/SettingsScreen.tsx',
        "hint={titles.join(' · ')}",
        "hint={'Rota guard · Sender addresses'}",
      ],
      [
        'settings/SettingsScreen.tsx',
        '<div className="settings-savebar-slot" ref={setSlot} />',
        '<div className="settings-savebar-slot" ref={setSlot}><button className="btn primary">Save rota guard</button><button className="btn primary">Save senders</button></div>',
      ],
    ],
  },
  'portal-events': {
    app: 'client',
    page: C + 'client/page.tsx',
    layouts: [C + 'client/layout.tsx'],
    pathname: '/client',
    db: portalDb,
  },
  'portal-event': {
    app: 'client',
    page: C + 'client/events/[id]/page.tsx',
    layouts: [C + 'client/layout.tsx'],
    params: { id: 'e1' },
    pathname: '/client/events/e1',
    db: { ...portalDb, client_events_v: [R.portalEvents[1]] },
  },
  'portal-event-done': {
    app: 'client',
    page: C + 'client/events/[id]/page.tsx',
    layouts: [C + 'client/layout.tsx'],
    params: { id: 'e2' },
    pathname: '/client/events/e2',
    db: { ...portalDb, client_events_v: [R.portalEvents[2]] },
  },
};

export default { ...base, ...extra(profileTab) };

export { iso, C };
